spring:
  application:
    name: wishlist
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGO_DB_URI:mongodb://localhost:27017/wish_list}
server:
  port: 8080
  shutdown: graceful

swagger:
  server:
    url: ${SWAGGER_SERVER_URL:http://localhost:8080}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /
