version: '2'

networks:
  app-tier:
    driver: bridge

services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    networks:
      - app-tier
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "27017:27017"
